name: Publish Workflow

permissions:
  packages: write
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run compile

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@sportvot'

      - name:
          Configure Git for pushing commits
          # Embed the access token directly into the remote URL so that the gh-pages library can pick it up
        run: |
          git config --global user.email "nirzon@sportvot.com"
          git config --global user.name "nirzon47"
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
